### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by ghost** [DerFetzer/open-smartpad#1]
Do I flash it with the USB port on the smartpad or do I need an adapter?

**Comment by DerFetzer** [comment]
Hi @vektrix1,

sorry for my late reply. I by mistake did not activate watching this repository so I got no notification for your issue.

Unfortunately I did not understand how the stock bootloader works so you have to flash the HID bootloader mentioned in README with SWD interface on the board (CN2) first. After this it will be possible to flash via USB.

Feel free to ask if further questions come up.

**Comment by ghost** [comment]
Ah, thank you.
